version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DATABASE_URL="postgresql://postgres:postgres@localhost:5433/sosmed"
    ports:
      - '3090:3090'
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - '5433:5433'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sosmed
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
