version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    command: sh -c "pnpm install && pnpm run dev"

volumes:
  mongo-data:
