import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Montserrat } from 'next/font/google'
import Navbar from "../components/navbar/NavbarHomes";
import { ViewTransitions } from 'next-view-transitions'

const montserrat = Montserrat({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
    <html lang="en">
      <body className={montserrat.className}>
        <Navbar />
        <div className="mx-auto w-[750px] max-w-full px-5 pb-10 pt-28">
          {children}
        </div>
      </body>
    </html>
  </ViewTransitions>
  );
}
