#!/bin/bash

# Jalankan npm format
npm run format || {
    echo 'please fix format' >&2
    exit 1
}

# Jalankan lint
npm run lint || {
    echo 'Linting failed, trying to fix issues...' >&2
    npm run lint:fix

    # Periksa apakah ada perubahan setelah lint:fix
    if [ -n "$(git status --porcelain)" ]; then
        echo 'Changes made by lint:fix. Adding changes to commit...'
        git add . # Tambahkan semua perubahan
        echo 'All changes added. Please proceed with your commit.'
        exit 0
    else
        echo 'No changes made by lint:fix. Exiting.' >&2
        exit 1
    fi
}

# Jika linting berhasil, lanjutkan
echo 'Linting passed.'
echo 'All checks passed.'
