name: Auto Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache pnpm
        uses: actions/cache@v3
        with:
          path: ~/.cache/pnpm
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.4
        with:
          node-version: '21'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 'latest'
          run_install: true

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build the project
        run: pnpm run build || { echo "Build failed"; exit 1; }

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        run: |
          rsync -avz --delete-after --progress \
          --exclude 'node_modules' \
          --exclude '.git' \
          -e "ssh -o StrictHostKeyChecking=no" \
          ./ root@${{ secrets.VPS_IP }}:${{ secrets.VPS_PATH }}

      - name: Restart Application
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.VPS_IP }} << 'EOF'
          cd /root/asepharyana.my.id
          pm2 status web || /root/.nvm/versions/node/v20.17.0/bin/pm2 start npm --name "web" -- start
          pm2 restart web
          EOF
