name: Auto Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Verify PNPM Installation
        run: pnpm --version  # Memverifikasi bahwa pnpm telah terinstal

      - name: Install dependencies
        run: pnpm install

      - name: Build the project
        run: pnpm run build

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        run: |
          rsync -avz --delete-after --progress \
          -e "ssh -o StrictHostKeyChecking=no" \
          ./ root@${{ secrets.VPS_IP }}:${{ secrets.VPS_PATH }}

      - name: Restart Application
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.VPS_IP }} << 'EOF'
          cd /root/asepharyana.my.id
          pm2 restart web || pm2 start npm --name "web" -- start
          EOF
